In [5]:
import pandas as pd

# ---------------------------
# TABLA GRUPOS
# ---------------------------
grupos = pd.DataFrame({
    "id_grupo": [1, 2, 3, 4],
    "nombre_grupo": ["1A", "2A", "3B", "4B"],
    "grado": [1, 2, 3, 4],
    "turno": ["Matutino", "Matutino", "Vespertino", "Matutino"]
})

# ---------------------------
# TABLA ALUMNOS
# ---------------------------
alumnos = pd.DataFrame({
    "id_alumno": [1, 2, 3, 4, 5, 6, 7, 8],
    "nombre": ["Juan", "María", "Pedro", "Ana", "Luis", "Sofía", "Carlos", "Daniela"],
    "apellido": ["Pérez", "López", "García", "Hernández", "Martínez", "Ramírez", "Torres", "Vega"],
    "edad": [6, 7, 7, 8, 9, 9, 10, 10],
    "id_grupo": [1, 1, 2, 2, 3, 3, 4, 4]
})

# ---------------------------
# TABLA MATERIAS
# ---------------------------
materias = pd.DataFrame({
    "id_materia": [1, 2, 3, 4],
    "nombre_materia": ["Matemáticas", "Español", "Ciencias", "Historia"]
})

# ---------------------------
# TABLA CALIFICACIONES
# ---------------------------
calificaciones = pd.DataFrame({
    "id_calificacion": [1,2,3,4,5,6,7,8,9,10,11,12],
    "id_alumno": [1,1,2,2,3,3,4,5,6,7,8,8],
    "id_materia": [1,2,1,3,2,4,1,2,3,4,1,2],
    "calificacion": [8.5, 5.5, 9.0, 7.0, 6.0, 4.0, 10.0, 7.5, 6.5, 8.0, 5.0, 9.5]
})

# Guardar en CSV
grupos.to_csv("grupos.csv", index=False)
alumnos.to_csv("alumnos.csv", index=False)
materias.to_csv("materias.csv", index=False)
calificaciones.to_csv("calificaciones.csv", index=False)

print("Archivos CSV creados correctamente.")

Archivos CSV creados correctamente.

In [7]:
grupos = pd.read_csv("grupos.csv")
alumnos = pd.read_csv("alumnos.csv")
materias = pd.read_csv("materias.csv")
calificaciones = pd.read_csv("calificaciones.csv")

print("Datos cargados desde CSV correctamente.")

Datos cargados desde CSV correctamente.

In [9]:
grupos.head()

   id_grupo nombre_grupo  grado       turno
0         1           1A      1    Matutino
1         2           2A      2    Matutino
2         3           3B      3  Vespertino
3         4           4B      4    Matutino

In [11]:
alumnos.head()

   id_alumno nombre   apellido  edad  id_grupo
0          1   Juan      Pérez     6         1
1          2  María      López     7         1
2          3  Pedro     García     7         2
3          4    Ana  Hernández     8         2
4          5   Luis   Martínez     9         3

In [13]:
materias.head()

   id_materia nombre_materia
0           1    Matemáticas
1           2        Español
2           3       Ciencias
3           4       Historia

In [15]:
calificaciones.head()

   id_calificacion  id_alumno  id_materia  calificacion
0                1          1           1           8.5
1                2          1           2           5.5
2                3          2           1           9.0
3                4          2           3           7.0
4                5          3           2           6.0

In [6]:
import sqlite3

# Conectar o crear base de datos
conn = sqlite3.connect("escuela_primaria.db")
cursor = conn.cursor()

# Eliminar tablas si ya existen
cursor.execute("DROP TABLE IF EXISTS calificaciones")
cursor.execute("DROP TABLE IF EXISTS alumnos")
cursor.execute("DROP TABLE IF EXISTS materias")
cursor.execute("DROP TABLE IF EXISTS grupos")

# Crear tabla grupos
cursor.execute("""
CREATE TABLE grupos (
    id_grupo INTEGER PRIMARY KEY,
    nombre_grupo TEXT NOT NULL,
    grado INTEGER NOT NULL,
    turno TEXT NOT NULL
)
""")

# Crear tabla alumnos
cursor.execute("""
CREATE TABLE alumnos (
    id_alumno INTEGER PRIMARY KEY,
    nombre TEXT NOT NULL,
    apellido TEXT NOT NULL,
    edad INTEGER NOT NULL,
    id_grupo INTEGER,
    FOREIGN KEY (id_grupo) REFERENCES grupos(id_grupo)
)
""")

# Crear tabla materias
cursor.execute("""
CREATE TABLE materias (
    id_materia INTEGER PRIMARY KEY,
    nombre_materia TEXT NOT NULL
)
""")

# Crear tabla calificaciones
cursor.execute("""
CREATE TABLE calificaciones (
    id_calificacion INTEGER PRIMARY KEY,
    id_alumno INTEGER,
    id_materia INTEGER,
    calificacion REAL,
    FOREIGN KEY (id_alumno) REFERENCES alumnos(id_alumno),
    FOREIGN KEY (id_materia) REFERENCES materias(id_materia)
)
""")

conn.commit()
print("Base de datos y tablas creadas correctamente.")

Base de datos y tablas creadas correctamente.

In [8]:
grupos.to_sql("grupos", conn, if_exists="append", index=False)
alumnos.to_sql("alumnos", conn, if_exists="append", index=False)
materias.to_sql("materias", conn, if_exists="append", index=False)
calificaciones.to_sql("calificaciones", conn, if_exists="append", index=False)

print("Datos insertados en SQLite correctamente.")

Datos insertados en SQLite correctamente.

In [10]:
query = "SELECT * FROM alumnos"
df = pd.read_sql_query(query, conn)
df

   id_alumno   nombre   apellido  edad  id_grupo
0          1     Juan      Pérez     6         1
1          2    María      López     7         1
2          3    Pedro     García     7         2
3          4      Ana  Hernández     8         2
4          5     Luis   Martínez     9         3
5          6    Sofía    Ramírez     9         3
6          7   Carlos     Torres    10         4
7          8  Daniela       Vega    10         4

In [16]:
query = """
SELECT alumnos.id_alumno,
       alumnos.nombre,
       alumnos.apellido,
       grupos.nombre_grupo,
       grupos.grado,
       grupos.turno
FROM alumnos
INNER JOIN grupos ON alumnos.id_grupo = grupos.id_grupo;
"""

df = pd.read_sql_query(query, conn)
df

   id_alumno   nombre   apellido nombre_grupo  grado       turno
0          1     Juan      Pérez           1A      1    Matutino
1          2    María      López           1A      1    Matutino
2          3    Pedro     García           2A      2    Matutino
3          4      Ana  Hernández           2A      2    Matutino
4          5     Luis   Martínez           3B      3  Vespertino
5          6    Sofía    Ramírez           3B      3  Vespertino
6          7   Carlos     Torres           4B      4    Matutino
7          8  Daniela       Vega           4B      4    Matutino

In [20]:
query = """
SELECT alumnos.id_alumno,
       alumnos.nombre,
       alumnos.apellido,
       calificaciones.calificacion
FROM alumnos
LEFT JOIN calificaciones ON alumnos.id_alumno = calificaciones.id_alumno;
"""

df = pd.read_sql_query(query, conn)
df

    id_alumno   nombre   apellido  calificacion
0           1     Juan      Pérez           5.5
1           1     Juan      Pérez           8.5
2           2    María      López           7.0
3           2    María      López           9.0
4           3    Pedro     García           4.0
5           3    Pedro     García           6.0
6           4      Ana  Hernández          10.0
7           5     Luis   Martínez           7.5
8           6    Sofía    Ramírez           6.5
9           7   Carlos     Torres           8.0
10          8  Daniela       Vega           5.0
11          8  Daniela       Vega           9.5

In [22]:
query = """
SELECT alumnos.nombre,
       alumnos.apellido,
       materias.nombre_materia,
       calificaciones.calificacion,
       CASE
            WHEN calificaciones.calificacion >= 6 THEN 'Aprobado'
            ELSE 'Reprobado'
       END AS estado
FROM calificaciones
INNER JOIN alumnos ON calificaciones.id_alumno = alumnos.id_alumno
INNER JOIN materias ON calificaciones.id_materia = materias.id_materia;
"""

df = pd.read_sql_query(query, conn)
df

     nombre   apellido nombre_materia  calificacion     estado
0      Juan      Pérez    Matemáticas           8.5   Aprobado
1      Juan      Pérez        Español           5.5  Reprobado
2     María      López    Matemáticas           9.0   Aprobado
3     María      López       Ciencias           7.0   Aprobado
4     Pedro     García        Español           6.0   Aprobado
5     Pedro     García       Historia           4.0  Reprobado
6       Ana  Hernández    Matemáticas          10.0   Aprobado
7      Luis   Martínez        Español           7.5   Aprobado
8     Sofía    Ramírez       Ciencias           6.5   Aprobado
9    Carlos     Torres       Historia           8.0   Aprobado
10  Daniela       Vega    Matemáticas           5.0  Reprobado
11  Daniela       Vega        Español           9.5   Aprobado

In [24]:
query = """
SELECT grupos.nombre_grupo,
       grupos.grado,
       ROUND(AVG(sub.promedio_alumno), 2) AS promedio_grupo
FROM grupos
INNER JOIN alumnos ON grupos.id_grupo = alumnos.id_grupo
INNER JOIN (
    SELECT id_alumno,
           AVG(calificacion) AS promedio_alumno
    FROM calificaciones
    GROUP BY id_alumno
) sub ON alumnos.id_alumno = sub.id_alumno
GROUP BY grupos.id_grupo;
"""

df = pd.read_sql_query(query, conn)
df

  nombre_grupo  grado  promedio_grupo
0           1A      1            7.50
1           2A      2            7.50
2           3B      3            7.00
3           4B      4            7.63

In [26]:
query = """
SELECT *
FROM alumnos
WHERE id_alumno IN (
    SELECT id_alumno
    FROM calificaciones
);
"""

df = pd.read_sql_query(query, conn)
df

   id_alumno   nombre   apellido  edad  id_grupo
0          1     Juan      Pérez     6         1
1          2    María      López     7         1
2          3    Pedro     García     7         2
3          4      Ana  Hernández     8         2
4          5     Luis   Martínez     9         3
5          6    Sofía    Ramírez     9         3
6          7   Carlos     Torres    10         4
7          8  Daniela       Vega    10         4

In [28]:
query = """
SELECT *
FROM alumnos
WHERE id_alumno NOT IN (
    SELECT id_alumno
    FROM calificaciones
);
"""

df = pd.read_sql_query(query, conn)
df

Empty DataFrame
Columns: [id_alumno, nombre, apellido, edad, id_grupo]
Index: []

In [ ]:
conn.close()
print("Conexión cerrada correctamente.")